project_name: mpdq

before:
  hooks:
    - go mod download

builds:
  - id: default
    binary: mpdq
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: ./main.go
    ldflags:
      - -s -w
  - id: homebrew
    binary: mpdq
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - arm64
    main: ./main.go
    ldflags:
      - -s -w

archives:
  - id: default
    builds: [default]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      386: i386
      darwin: macos
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    format: binary
  - id: homebrew
    builds: [homebrew]
    replacements:
      386: i386
      darwin: macos
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  ids: ["default", "homebrew"]
  prerelease: auto

brews:
  - ids: ["homebrew"]
    name: mpdq
    tap:
      owner: jfreeland
      name: homebrew-tap
    commit_author:
      name: "Joey Freeland"
      email: "joey@free.land"
    folder: Formula
    homepage: https://github.com/jfreeland/mpdq
    description: "A cli tool to parse MPEG-DASH manifests"
    url_template: "https://github.com/jfreeland/mpdq/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

checksum:
  disable: true

changelog:
  skip: true
