name: release

on:
  push:
    tags: [ "v*.[0-99]" ] # only a valid semver tag

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow --tags
      - name: Install Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
